# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3ddb93a1ffd13bcc076a6f82943e22e47152b7cfb3709720b23d02a185f072adc380b8b561b10ac8ce79e033701ac1cc3b0176f2ae9ce4c880667b50c3d3ff8

test:
  secret_key_base: 845a5c6d536bfe194d70856c1a4f832dfcb469a735059fddca2e7db1350beabe299d5cdad730b0e06f5f6fde3ca1ce602d80a63b12a0912faa95845b7bd29cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
